### PR TITLE
Bump version in build post-release

### PR DESCRIPTION
**Pull request by ashawley**
- Bump to 1.14.3
- Update MiMa to 1.14.2
- Update examples. to 1.14.2
- Give more recent snapshot example

### CODE REVIEW

**Comment by non** [comment]
@ashawley do you want to target the `1.14.x` branch with this? I'd like to bump master to `1.15.0` so we can start doing things like e.g. removing 2.10.

**Comment by ashawley** [comment]
Sure, I'll work on that.

**Comment by ashawley** [comment]
@non Changing the base brought in a bunch of more changes. I've merged last master in to 1.14.x and pushed up a new 1.14.x, since that's what you had done previously.  Rebasing this onto the new 1.14.x has the single changes in this PR.  Hopefully, that's what you were looking for here.

**Comment by non** [comment]
That sounds fine. I had imagined possibly waiting to backport the other changes from master to 1.14.x until we need them, but this works too.

👍

**Comment by ashawley** [comment]
Do you want me to do a version of this for 1.15.0?  Or were you already working on it?

**Pull request merged**
