### PR TITLE
Force posNum and negNum generators to always return values

### PR DESCRIPTION
**Pull request by zakpatterson**
Fixes (part of) #568.

### CODE REVIEW

**Comment by non** [comment]
This looks good. Would you be willing to add one other change? I think unless our `Numeric[T]` is actually a `Fractional[T]` we can do something even simpler, i.e.

```scala
def posNum[T](implicit num: Numeric[T], c: Choose[T]): Gen[T] = {
  import num._
  num match {
    case _: Fractional[_] =>
      sized(n => c.choose(zero, max(fromInt(n), one)).suchThat(_ != zero))
    case _ =>
      sized(n => c.choose(one, max(fromInt(n), one))
  }
}
```

The reason this might be better is that if `n` is one, the fractional types will still be able to generate plenty of non-zero values, but the integral types will be generating zero 50% of the time (resulting in more retries).

**Comment by zakpatterson** [comment]
Yes, that makes sense. I'm playing with it now and I'll push tonight.

**Comment by zakpatterson** [comment]
While I'm staring at this, is there a reason that negNum is not just 

```scala
  def negNum[T](implicit num: Numeric[T], c: Choose[T]): Gen[T] = posNum[T].map(num.negate(_))
```

**Comment by non** [comment]
@zakpatterson Using negation on negative numbers can be dangerous (since `-Int.MinValue == Int.MinValue`) but I think your change makes sense.

This looks good. Thanks! 👍

**Comment by zakpatterson** [comment]
Thanks for the review @non, I learned something.

**Comment by non** [comment]
I think the build failure was transient, I'm retrying now.

**Pull request merged**
