### PR TITLE
Upgrade Scala.js to 1.0.0

### PR DESCRIPTION
**Pull request by xerial**
Finally Scala.js 1.0.0 has been released https://github.com/scala-js/scala-js/releases/tag/v1.0.0

### CODE REVIEW

**Comment by ashawley** [comment]
Would you be willing to update the Scala.js example to 1.0 while you're at it?

**Comment by xerial** [comment]
Sure. Let me try :)

**Comment by xerial** [comment]
@ashawley Done. The next target version is 1.14.3 or 1.15.0?

**Comment by ashawley** [comment]
Thanks!

The current version is 1.14.3, the next version will be 1.15.0.  

We can look in to backporting to 1.14.x and pushing a tag like we did most recently in #592, for example.

**Comment by ashawley** [comment]
LGTM!  The mima check fails because 1.14.3 artifacts don't exist, but we can resolve that as I mentioned previously.

**Comment by larsrh** [comment]
It would be great if you could release 1.14.3 with sjs 1.0 support. That way, it wouldn't trigger a wave of version bumps across the ecosystem.

**Comment by ashawley** [comment]
Yes, that's what is being worked on in #623.

**Comment by ashawley** [comment]
1.14.3 artifacts for Scala.js have been released.

**Comment by xerial** [comment]
@ashawley Awesome. Thank you so much 😄

**Pull request merged**
