### PR TITLE
Always show seed for failing property check

### PR DESCRIPTION
**Pull request by ryanpbrewster**
This copies the current behavior of `propertyWithSeed(..., None)` into `property(...)`

### CODE REVIEW

**Comment by ryanpbrewster** [comment]
I believe this will address https://github.com/rickynils/scalacheck/issues/400

**Comment by SethTisue** [comment]
rebase?

**Comment by ryanpbrewster** [comment]
done

**Comment by SethTisue** [comment]
is someone knowledgeable enough to review this?

**Comment by ashawley** [comment]
It looks good to me, but @non is the seed expert.

**Comment by ryanpbrewster** [comment]
Note for reviewer: this is basically copy-pasting the implementation from L111, the `PropertyWithSeedSpecifier` class. This class will always show the seed for a failing test case.

((Effectively the only change here is adding a call to `.viewSeed(fullName)` to the end of `Prop.delay(p)`. Let me know if there's anything else I can add here.))

**Comment by SethTisue** [comment]
perhaps add a test that illustrates the change...?

**Pull request merged**
