### PR TITLE
Add Gen.fix to make recursive generators cleaner

### PR DESCRIPTION
**Pull request by johnynek**
same idea as https://github.com/typelevel/cats/pull/3208 but particular to Gen.

Gen and Parsers are what motivated the 3208 PR.

### CODE REVIEW

**Comment by ashawley** [comment]
What's the example do?  It's building lists that terminate with numbers higher than 5?

```scala
val fixGen =
  Gen.fix[List[Int]] { recurse =>
    Gen.choose(0, 10).flatMap { idx =>
      if (idx < 5) recurse.map(idx :: _)
      else Gen.const(idx :: Nil)
    }
  }
```

**Comment by johnynek** [comment]
Yes. I didn’t want to make a longer example such as a tree or JSON or something in the comment and I wanted to test the same thing that I put in the comment.

It’s probably not a great example because in this case there are ways to do this without recursion.

**Comment by ashawley** [comment]
Yeah, I was also wondering if there was a better example to use.  I do like this example for one reason:  Writing with existing combinators is clunky, because I tried:

```scala
val fixGen = {
  Gen.nonEmptyListOf(Gen.choose(0, 9)).map { ns =>
    val idx = ns.indexWhere(_ >= 5)
    ns.take(if (idx == -1) ns.size - 1 else idx + 1)
  }
}
```

Maybe there is a built-in generator that could be rewritten using this syntax as an example?

**Comment by ashawley** [comment]
This construct seems pretty useful.  Should we elevate it by giving it a better name for visibility sake? Could we rename to something like `from`, `of`, `until` or `continually`?:

```scala
val listGen = Gen.of { recurse: Gen[List[Int]] =>
  ...
}
```

**Comment by johnynek** [comment]
Fix is the name for this traditionally: fix(f) = f(fix(f)).

I think the name should explain something about recursion. If you aren’t doing recursion you don’t need this.

What about `def recursive`?

**Comment by ashawley** [comment]
I agree.  I guess I prefer a verb or an adverb, so even just `recur`.  We can stew on it for a few days.  This could be part of 1.15.0 which should be ready soon.

PS. I'm familiar with fixed point since I used to Scheme occasionally.  I won't suggest `Gen.y`, though.

**Comment by ashawley** [comment]
After some time, I haven't had any strong feelings about a better name, so should we go with `Gen.recursive`?  It works for me.

**Comment by larsrh** [comment]
fast-check calls it `letrec`

**Comment by ashawley** [comment]
That would seem to give evidence for naming it `recursive` then.  I'm going to merge and follow-up with a commit that renames it.

**Pull request merged**
