### PR TITLE
Use implicit in Shrink.suchThat example

### PR DESCRIPTION
**Pull request by ashawley**
Follow-up to #484.

### CODE REVIEW

**Comment by ashawley** [comment]
I don't think using `implicitly` is possible.  That's probably the reason there aren't a lot of examples for Shrink that use it.  There's no way around that.

**Comment by koterpillar** [comment]
Yes, I wondered that too - perhaps it will be better to make an example with a custom type to avoid possible conflicts?

**Comment by ashawley** [comment]
Yes, while the use of implicits for shrink instances in `forAll` is a convenience, the scoping collisions is a disadvantage.

**Comment by ashawley** [comment]
Yup, Hedgehog has coupled shrink with the generator in their GenT type:

https://github.com/hedgehogqa/scala-hedgehog/blob/28a8a9d/core/shared/src/main/scala/hedgehog/core/GenT.scala

**Pull request merged**
