### PR TITLE
Upgrade Scala.js to 1.0.0-RC1

### PR DESCRIPTION
**Pull request by xerial**

### CODE REVIEW

**Comment by ashawley** [comment]
Thanks for working on this.  The pressing need is to release a 1.14.2 artifact for ScalaJS 1.0.0-RC1.  I'll work on using this change over on the 1.14.x branch.  Thanks again.

**Comment by ashawley** [comment]
There is a reference to ScalaJS 1.0.0-M8 in a shell script, `release.sh`, that needs updating, as well.  Unfortunately, the script is not used by Travis, so Travis doesn't catch that defect.

**Comment by xerial** [comment]
@ashawley Thanks. Feel free to close this PR as you know better than I about the release process of scalacheck.

**Comment by xerial** [comment]
I'll check release.sh just in case.

**Comment by xerial** [comment]
@ashawley Updated the release script as well and squashed the commits onto the master.

**Comment by ashawley** [comment]
Sorry for the delay.

I'm going to close this, and going to work on publishing for Scala.js 1.0.0-RC2 in a new ScalaCheck 1.14.3 release, which see #591.

**Comment by xerial** [comment]
Sounds good. Thanks @ashawley

**Pull request closed without merging**
