### PR TITLE
Fix Off By One Error In JavaTimeChoose

### LINKED ISSUE #762: Invalid bounds in JavaTimeChoose
Version: 1.15.3

Caused by: org.scalacheck.Gen$Choose$IllegalBoundsError: invalid bounds: low=1, high=0
	at org.scalacheck.Gen$Choose$$anon$8.choose(Gen.scala:475)
	at org.scalacheck.Gen$Choose$$anon$8.choose(Gen.scala:473)
	at org.scalacheck.Gen$Choose$$anon$12.choose(Gen.scala:596)
	at org.scalacheck.Gen$.choose(Gen.scala:637)
	at org.scalacheck.time.JavaTimeChoose$$anon$2.$anonfun$choose$3(JavaTimeChoose.scala:68)
	at org.scalacheck.time.JavaTimeChoose$$anon$2.$anonfun$choose$3$adapted(JavaTimeChoose.scala:55)

Looks like the case where, in #chooseInstant, epochSecond != min.getEpochSecond and epochSecond == max.getEpochSecond == 0.

### PR DESCRIPTION
**Pull request by isomarcte**
The minimum value of nanoseconds for both Duration and Instant should be 0, unless the second value == the minimum bound's second value. It was incorrectly encoded as 1.

Fixes #762

### CODE REVIEW

**Comment by isomarcte** [comment]
@larsrh @ashawley any thoughts here?

**Review by ashawley — CHANGES_REQUESTED** [review]
Worth adding a test or improving an exiting one to capture the failure?

**Comment by isomarcte** [comment]
@ashawley will do

**Comment by isomarcte** [comment]
@ashawley test added

**Review by ashawley — APPROVED** [review]

**Comment by ashawley** [comment]
Thanks for adding tests.

**Pull request merged**
