### PR TITLE
Cut out a bunch of Travis builds to see if things are better.

### PR DESCRIPTION
**Pull request by non**
It's possible this is too aggressive (or not aggressive enough) but I
wanted to see how much faster and more reliable things would be with
these settings.

### CODE REVIEW

**Comment by non** [comment]
Well, things are still super flaky (and it takes awhile to get scheduled). On the up-side, we only had 14 jobs and the longest took only 8 minutes, which is an improvement.

**Comment by non** [comment]
@ashawley What do you think? It might be nice to do something like this (at least until Travis gets less flaky). For the last couple days I think we've all had to baby-sit these Travis builds and click restart on the failed jobs which is annoying.

**Comment by ashawley** [comment]
Yeah, makes sense.  Looks like it cuts the build times in half.

**Comment by SethTisue** [comment]
I don't know the history of `SBT_PARALLEL`. would it make sense to use `include:` to add a *single* job with `SBT_PARALLEL=false`?

and if that *doesn't* make sense, then I wonder if it might make more sense to eliminate `SBT_PARALLEL` entirely

**Pull request merged**
