### PR TITLE
Remove support for 2.10.

### LINKED ISSUE #505: drop Scala 2.10 support

### PR DESCRIPTION
**Pull request by non**
This removes 2.10 from the build and Travis.

As a result it also simplifies the `build.sbt` slightly.

Resolves #505

### CODE REVIEW

**Comment by ashawley** [comment]
Technically, we might want to merge after the 1.14.1 release, after we start the 1.14.x branch and begin the work on 1.15.

**Comment by SethTisue** [comment]
> we might want to merge after the 1.14.1 release

hmmm... skeptical. 2.10 users have been living with the existing 1.14 artifacts a long time already, is there anything in 1.14.1 that it's actually important to offer them?

**Comment by ashawley** [comment]
We'll be holding off on this until 1.14.1 is released.

**Comment by non** [comment]
Now that we released 1.14.1 I'm planning to merge this.

Any objections? @SethTisue @ashawley

**Comment by SethTisue** [comment]
needs rebase, though :-)

**Comment by ashawley** [comment]
Fixed in #572.

**Pull request closed without merging**
