### PR TITLE
Fix Scala.js 1.0 and Scala 2.10 in build

### PR DESCRIPTION
**Pull request by ashawley**
Related to #555.

### CODE REVIEW

**Comment by ashawley** [comment]
Travis was trying to run Scala.js 0.6 with Scala 2.10, but sbt would silently fail to set 2.10.7 for the `js` project:

```
[info] Setting Scala version to 2.10.7 on 2 projects.
[info] Excluded 2 projects, run ++ 2.10.7 -v for more details.
```

This would cause the build to just run with 2.13.

The fix here makes Travis run the correct Scala version.  One thing I hadn't considered is MiMa will fail here until 1.14.1 is published for Scala.js 0.6 and Scala 2.10, which see #555.

**Comment by non** [comment]
I'm going to apply this locally and publish 1.14.1 for 2.10 on JS -- I think that's what the build failure is about.

**Comment by non** [comment]
Steps I took to publish 1.14.1 for 2.10 and ScalaJS 0.6.28:

1. Created `1.14.x` branch
2. Cherry-picked this commit and resolved the conflict
3. Read `release.sh`
4. Locally-edited `build.sbt` and set `isRelease` to `true`
5. Ran `SCALAJS_VERSION="0.6.28" sbt`
6. In SBT ran `++ 2.10.7` and then `js/publishSigned`
7. In Sonatype, closed and released the staging repo

This should resolve the immediate problem in #555 and should also allow MiMA checks for JS on 2.10 to start working.

**Comment by ashawley** [comment]
> I think that's what the build failure is about.

Yes, precisely.  I somehow forgot to mention that above.

**Comment by ashawley** [comment]
> should also allow MiMA checks for JS on 2.10 to start working

Yes, I restarted the build and now we're green here. Thanks, Erik!

**Pull request merged**
